questions/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from questions import views


urlpatterns = patterns('',
    url(r'^$', views.questions, name="questions_home"),
    url(r'^add/$', views.add_question, name="add_question"),
    url(r'^answer/([\w+])/$', views.answer_vote, name="answer_vote"),
    url(r'^(?P<questionslug>[\w-]+)/add-answer/$', views.add_answer, name="add_answer"),
    url(r'^(?P<questionslug>[\w-]+)/$', views.question, name="question"),
    

)

urls.py
from django.conf.urls.defaults import *
import django.views.static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from news.views import index
from news.feeds import LatestEntries
from users.views import *
from custom_comments.views import comment_reply

feeds = {
    'latest': LatestEntries,
}

urlpatterns = patterns('',
    url(r'^$', index, name="home"),
    url(r'^invite_user/$', invite_user, name="invite_user"),
    url(r'^seen_voting_reminder/$', seen_voting_reminder, name="seen_voting_reminder"),
    url(r'^invite/(?P<key>[\w-]+)$', activate_invited_user, name="activate_invited_user"),
    url(r'^profile/edit_bio$', edit_bio, name="edit_bio"),
    url(r'^profile/$', user_profile, name="user_profile"),
    url(r'^profile/(?P<slug>[\w-]+)/all_posts$', all_posts, name="all_posts"),
    url(r'^profile/(?P<slug>[\w-]+)$', profile, name="profile"),
    url(r'^comment/reply/(?P<hashkey>[\w-]+)/(?P<id>[\w-]+)$', comment_reply, name="comment_reply"),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, name="latest_feed"),
    (r'^news/', include('news.urls')),
    (r'^questions/', include('questions.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^admin/', include(admin.site.urls)),
)


# for the development server static files
urlpatterns += patterns('',

    # CSS, Javascript and IMages
    (r'^photos/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/photos',
        'show_indexes': settings.DEBUG}),
    (r'^images/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/images',
        'show_indexes': settings.DEBUG}),
    (r'^cache/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/cache',
        'show_indexes': settings.DEBUG}),
    (r'^thumbs/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/thumbs',
        'show_indexes': settings.DEBUG}),
    (r'^css/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/css',
        'show_indexes': settings.DEBUG}),
    (r'^js/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/js',
        'show_indexes': settings.DEBUG}),
)

questions/models.py
from django.db import models
from datetime import datetime

from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.contrib.comments.models import Comment
from django.contrib.comments.signals import comment_was_posted
from django.template.loader import render_to_string

from users.models import Person


class QuestionManager(models.Manager):
    def filter(self):
        qs = super(QuestionManager, self).get_query_set()
        return qs.filter()

class Question(models.Model):
    date = models.DateTimeField()
    owner = models.ForeignKey(Person)
    question = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=200)
    votes = models.IntegerField(default="0")
    voters = models.ManyToManyField(Person, related_name="question_voters")
    is_published = models.BooleanField(default=True)

    def __unicode__(self):
        return self.question     

    def get_absolute_url(self):
        return "/questions/%s/" % self.slug
    
    def answers_count(self):
        answers = Answer.objects.filter(question=self)
        return answers.count() 
    
        
class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='to_question')
    owner = models.ForeignKey(Person)
    answer = models.TextField()
    date_added = models.DateTimeField(default=datetime.now())
    votes = models.IntegerField(default="0")
    voters = models.ManyToManyField(Person, related_name="answer_voters")
    is_published = models.BooleanField(default=True)
    
    def __unicode__(self):
        return "%s, %s" % (self.owner, self.answer)      

questions/forms.py
from django import forms
 
class AddQuestionForm(forms.Form):
    question = forms.CharField(max_length=200, label="* Question title")
    description = forms.CharField(widget=forms.Textarea, required=False, label="Extra information/details")

    
class AddAnswerForm(forms.Form):
    answer = forms.CharField(widget=forms.Textarea)
    
class SearchForm(forms.Form):
    q = forms.CharField(label='Search')

questions/views.py
# core python imports
from django.conf import settings
from django.core.urlresolvers import reverse
from datetime import timedelta, datetime
from PIL import Image
from cStringIO import StringIO
import os, md5
import smtplib
import re

# stuff from my app
from users.models import Person
from questions.models import Question, Answer
from questions.forms import AddQuestionForm, AddAnswerForm, SearchForm
from questions.data import find_questions
from slugify import get_slugify


# django stuff
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf


#render shortcut
def render(request, template, context_dict=None, **kwargs):
    return render_to_response(
        template, context_dict or {}, context_instance=RequestContext(request),
                              **kwargs
    )

def questions(request, qs=None, parameters={}):
        
    # if there's a search query
    if request.GET.get('q'):
        search_form = SearchForm(initial=request.GET)
        q = request.GET.get('q')
        questions = find_questions(q=q, qs=qs, **parameters)
        return render(request, "questions/questions.html", locals())
    else:
        search_form = SearchForm()
        
    questions = Question.objects.filter(is_published=True)

    return render(request, "questions/questions.html", locals())


def question(request, questionslug):
    question = get_object_or_404(Question, slug=questionslug)
    if not question.is_published:
        return Http404()
    
    
    if request.user.is_authenticated():
        person = request.user.get_profile()
    else:
        person = None
    
    answers = Answer.objects.filter(question=question)    
    
    if request.method == 'POST':
        form = AddAnswerForm(request.POST)
        if form.is_valid():
            person = request.user.get_profile()
            creation_args = {
                'answer': form.cleaned_data['answer'],
                'owner': person,
                'question': question,	
                'date_added': datetime.now(),
            }
            
            answer = Answer.objects.create(**creation_args)
            url = question.get_absolute_url()
            return HttpResponseRedirect(url)
    else:
        form = AddAnswerForm()
    
    
    #answers_list = []
    #for answer in Answer.objects.filter(question=question):
    #    if answer in (x.answer for x in vote_list):
    #        voted=True
    #    else:
    #        voted=False
    #    if answer.added_by == laowai:
    #        owner = True
    #    else: 
    #        owner = False
    #    answers_list.append(dict(answer=answer, voted=voted, owner=owner, vote_count=answer.vote_count))
    #answers = sorted(answers_list, reverse=True, key=lambda k: k['vote_count'])
    
    return render(request, "questions/question.html", locals())

@login_required
def add_question(request):
    
    if request.method == 'POST':
        form = AddQuestionForm(request.POST)
        if form.is_valid():
            # check if there's a similar question:
                # do something here to check...
            
            person = request.user.get_profile()
            slug = get_slugify(form.cleaned_data['question'])
            while(Question.objects.filter(slug__iexact=slug).count()):
                current_number_suffix_match = re.search("\d+$", slug)
                current_number_suffix = current_number_suffix_match and current_number_suffix_match.group() or 0
                next = str(int(current_number_suffix) +1)
                slug = re.sub("(\d+)?$", next, slug)
            creation_args = {
                        'question': form.cleaned_data['question'],
                        'description': form.cleaned_data['description'],
                        'owner': person,
                        'slug': slug,
                        'date': datetime.now(),
            }
                     
            
            question = Question.objects.create(**creation_args)
            
            url = reverse('question', args=[question.slug])
            return HttpResponseRedirect(url)
    else:
        form = AddQuestionForm()
    
    return render(request, "questions/forms/add_question.html", locals())

@login_required
def add_answer(request, questionslug):
    question = get_object_or_404(Question, slug=questionslug)
    if request.method == 'POST':
        form = AddAnswerForm(request.POST)
        if form.is_valid():
            person = request.user.get_profile()
            creation_args = {
                'answer': form.cleaned_data['answer'],
                'owner': person,
                'question': question,	
                'date_added': datetime.now(),
                'votes': 1,
            }
            
            answer = Answer.objects.create(**creation_args)
            url = question.get_absolute_url()
            return HttpResponseRedirect(url)
    else:
        form = AddAnswerForm()
    
    return render(request, "questions/forms/add_answer.html", locals())

@login_required
def answer_vote(request, id):
    answer = get_object_or_404(Answer, pk=id) 
    answer.votes += 1
    answer.voters.add(request.user.get_profile())
    answer.save()
    if answer.owner.karma is None:
        answer.owner.karma = 1
    else:
        answer.owner.karma += 1
    
    answer.owner.save()
    url = request.META.get('HTTP_REFERER','/')
    return HttpResponseRedirect(url)

templates/questions/question.html
{% extends "base.html" %}

{% block pagetitle %}{{ question.question }}{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$('#answer-form').submit(function() {
	$('#submit-answer').css('opacity', '0.5');
	$('#submit-answer').unbind('click');
});
</script>
{% endblock %}

{% block extracss %}
<style type="text/css">
.small {color: #999;}
.votes {
  color: #333;
  font-weight: bold;	
}

ul#answerlist {
  list-style-type: none;	
}

ul#answerlist li {
  margin-bottom: 30px;
  border-bottom: 3px dotted #e1e1e1;
  padding-bottom: 30px;	
}

#answerlist li p {
  margin-bottom: 5px;	
}

form {margin-top: 10px; width: 800px; float: left; padding: 20px 20px 0px 20px; background-color: #e1e1e1; margin-bottom: 30px;}
label {float: right; margin-left: 20px;}
textarea {float: left; margin: 0 20px 20px 0;}
input.button {width: 200px;}
p.note {
  margin-top: 0;	
}

.ding a:link, .ding a:visited {
    background-color: #e1e1e1;
    color: #666;
    display: block;
    float: left;
    font-weight: 900;
    height: 8px;
    margin-right: 5px;
    padding: 4px 4px 5px 5px;
    position: relative;
    top: 1px;
    width: 7px;
}

.ding a:hover {
  background-color: #D95700;
  color: #fff;
  text-decoration: none;
}

</style>
{% endblock %}

{% block addbutton %}
<a class="button" href="{% url add_question %}">Add Question</a>
{% endblock %}

{% block content %}

<h2>{{ question.question }}</h2>
<p class="small">Added by <a href="{% url profile question.owner.user.username %}">{{ question.owner.user.username }}</a> {{ question.date|timesince }} ago</p>
<p class="description"><em>{{ question.description }}</em></p>


{% if request.user.is_authenticated %}
<form id="answer-form" action="." method="post">
{% csrf_token %}
<textarea id="id_answer" rows="5" cols="40" name="answer"></textarea>
<p class="note"><strong>&laquo; Add your answer</strong><br/>Please try to give as much information as you can and answer clearly.</p>
<input id="submit-answer" type="submit" value="Submit answer" class="button">
</form>
{% else %}
<p><strong><a href="{% url auth_login %}">Login</a> or <a href="{% url registration_register %}">signup</a> to post an answer.</strong></p>
{% endif %}



{% if answers %}
<h3>Answers ({{ answers.count }})</h3>
<ul id="answerlist">
{% for answer in answers %}
	<li class="">
		<p>{{ answer.answer }}</p>
		<span class="small">
			{% if request.user.is_authenticated %}
			{% if request.user.get_profile in answer.voters.all %}{% else %}
				
			{% endif %}
			{% endif %}
			<span class="votes">{{ answer.votes }} point{{ answer.votes|pluralize }}</span> -
			Answered by <a href="{% url profile answer.owner.user.username %}">{{ answer.owner.user.username }}</a> - 
			{{ answer.date_added|timesince }} ago
		</span>
	</li>
{% endfor %}

{% else %}
{% endif %}


{% endblock %}

templates/questions/questions.html
{% extends "base.html" %}

{% load django_static %}

{% block pagetitle %}Questions{% endblock %}

{% block extracss %}
<style type="text/css">

</style>
{% endblock %}

{% block addbutton %}
<a class="button" href="{% url add_question %}">Add Question</a>
{% endblock %}

{% block content %}

{% include "snippets/search_bar.html" %}

<ol id="newslist">
{% for q in questions %}
	<li>
		<a href="{% url question q.slug %}">{{ q.question }}</a><br/>
		<span class="small">

			<a href="{% url profile q.owner.user.username %}">Added by {{ q.owner }}</a> - 
			{% if q.answers_count %}
				<a href="{% url question q.slug %}">{{ q.answers_count }} answer{{ q.answers_count|pluralize }}</a> - 
			{% else %}
				<a href="">Add an answer</a> - 
			{% endif %}
			{{ q.date|timesince }} ago
		
		
	</span>
	</li>
{% endfor %}
</ol>

{% endblock %}