news/urls.py
from django.conf.urls.defaults import *

from news.views import *

urlpatterns = patterns('',
    url(r'^$', news_home, name="news_home"),
    url(r'^item/(?P<hashkey>[\w-]+)/blocked$', news_blocked, name="news_blocked"),
    url(r'^item/(?P<hashkey>[\w-]+)/ding$', news_ding, name="news_ding"),
    url(r'^news_ding_ajax$', news_ding_ajax, name="news_ding_ajax"),
    url(r'^item/(?P<hashkey>[\w-]+)$', news_item, name="news_item"),
    url(r'^comment/(?P<id>[\w-]+)/ding$', comment_ding, name="comment_ding"),
    url(r'^add/$', add_news, name="add_news"),
)

urls.py
from django.conf.urls.defaults import *
import django.views.static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from news.views import index
from news.feeds import LatestEntries
from users.views import *
from custom_comments.views import comment_reply

feeds = {
    'latest': LatestEntries,
}

urlpatterns = patterns('',
    url(r'^$', index, name="home"),
    url(r'^invite_user/$', invite_user, name="invite_user"),
    url(r'^seen_voting_reminder/$', seen_voting_reminder, name="seen_voting_reminder"),
    url(r'^invite/(?P<key>[\w-]+)$', activate_invited_user, name="activate_invited_user"),
    url(r'^profile/edit_bio$', edit_bio, name="edit_bio"),
    url(r'^profile/$', user_profile, name="user_profile"),
    url(r'^profile/(?P<slug>[\w-]+)/all_posts$', all_posts, name="all_posts"),
    url(r'^profile/(?P<slug>[\w-]+)$', profile, name="profile"),
    url(r'^comment/reply/(?P<hashkey>[\w-]+)/(?P<id>[\w-]+)$', comment_reply, name="comment_reply"),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, name="latest_feed"),
    (r'^news/', include('news.urls')),
    (r'^questions/', include('questions.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^admin/', include(admin.site.urls)),
)


# for the development server static files
urlpatterns += patterns('',

    # CSS, Javascript and IMages
    (r'^photos/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/photos',
        'show_indexes': settings.DEBUG}),
    (r'^images/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/images',
        'show_indexes': settings.DEBUG}),
    (r'^cache/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/cache',
        'show_indexes': settings.DEBUG}),
    (r'^thumbs/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/thumbs',
        'show_indexes': settings.DEBUG}),
    (r'^css/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/css',
        'show_indexes': settings.DEBUG}),
    (r'^js/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT + '/js',
        'show_indexes': settings.DEBUG}),
)

news/models.py
from django.db import models
from urlparse import urlparse
from django.core.urlresolvers import reverse

from users.models import Person


class NewsItem(models.Model):
    owner = models.ForeignKey(Person)
    date = models.DateTimeField()
    url = models.URLField(blank=True, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField(blank=True, null=True)
    votes = models.PositiveIntegerField(default="0")
    hashkey = models.CharField(max_length=256)
    voters = models.ManyToManyField(Person, db_index=True, related_name="Voters", null=True, blank=True)
    blocked = models.PositiveIntegerField(default="0")
    
    def __unicode__(self):
        return self.title
        
    def is_blocked(self):
        blocked = False
        if self.blocked > 3:
            blocked = True
        
        return blocked
    
    def show_url(self):
        url = urlparse(self.url)
        return url.netloc
   
    def get_comment_count(self):
        from custom_comments.models import CommentWithVote
        count = CommentWithVote.objects.filter(object_pk=self.pk).count()
        return count
    
    def get_absolute_url(self):
        url = reverse('news_item', args=[self.hashkey])
        return url
    
    class Meta:
        ordering = ['-date']

news/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
import re
from urlparse import urlparse, urljoin

from users.models import Person
from news.models import *



class AddNewsForm(forms.Form):
    title = forms.CharField(required=True, label='* Title')
    url = forms.CharField(required=False, label='URL', 
        help_text="Use this if you're posting a link")
    text = forms.CharField(widget=forms.Textarea, required=False, label='Text',
        help_text="Use this if you're starting a discussion")
    as_user = forms.ModelChoiceField(required=False, queryset=Person.objects.filter(user__is_staff=True), 
        label="As user")
    
    
    def clean_url(self):
        # we just want to check that the URL is properly formed
        url = self.cleaned_data['url']
        data = urlparse(url)
        if not data.scheme:
            url = "http://%s" % url
                
        return url

users/forms.py
from django import forms


class InviteUserForm(forms.Form):
    email = forms.CharField(required=True)
    
    
class CompleteUserDetailsForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    
class EditBioForm(forms.Form):
    bio = forms.CharField(required=True, widget=forms.Textarea)

news/views.py
from django.conf import settings
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import auth
from django.template import RequestContext
from django.contrib.comments.models import Comment

from django.http import HttpResponseRedirect, HttpResponse 
from django.core.urlresolvers import reverse

import uuid
from datetime import datetime, timedelta

from users.models import *
from news.forms import *
from custom_comments.models import CommentWithVote

#render shortcut
def render(request, template, context_dict=None, **kwargs):
    return render_to_response(
        template, context_dict or {}, context_instance=RequestContext(request),
                              **kwargs
    )


def _get_news(request, latest=None):

#   1. filter all the news stories from the last week
#   2. sort them by combined score
#   3. return the news
#   The algorithm has to take account of the value of points, comments and then also 'freshness' 
    
    if latest:
        news = NewsItem.objects.all().order_by('-date')  
    
    else:   
        news_list = []
        for n in NewsItem.objects.all():
            time_difference = (datetime.now() - n.date)
            freshness = (int(time_difference.days) + 1) 
            n.combined_count = ((n.votes + n.get_comment_count()) / freshness) 
            news_list.append(n)

        news = sorted(news_list, reverse=True, key=lambda n: n.combined_count)

    return news[:20]

def index(request):
    news = _get_news(request)
    return render(request, "news/news_home.html", locals())
 
def news_home(request):
    news = _get_news(request, latest=True)
    latest = True
    return render(request, "news/news_home.html", locals())   


def news_item(request, hashkey):
    news_item = get_object_or_404(NewsItem, hashkey=hashkey)
    return render(request, "news/news_item.html", locals())

@login_required
def news_ding(request, hashkey):
    item = get_object_or_404(NewsItem, hashkey=hashkey)
    item.votes += 1
    item.voters.add(request.user.get_profile())
    item.save()
    
    if item.owner.karma == "0":
        item.owner.karma = 1
    else:
        item.owner.karma += 1
    
    item.owner.save()
    
    url = request.META.get('HTTP_REFERER','/')
    return HttpResponseRedirect(url)

def news_ding_ajax(request):
    if request.GET.get('xhr'):
        news_item = get_object_or_404(NewsItem, pk=request.GET.get('id'))
        news_item.votes +=1
        news_item.voters.add(request.user.get_profile())
        news_item.save()
        
        if news_item.owner.karma is None:
            news_item.owner.karma = 1
        else:
            news_item.owner.karma +=1
        
        news_item.owner.save()
        
        return HttpResponse(news_item.votes)
    return

@login_required
def news_blocked(request, hashkey):
    item = get_object_or_404(NewsItem, hashkey=hashkey)
    if item.blocked is None:
        item.blocked = 1
    else:
        item.blocked +=1
    
    item.save()
    url = request.META.get('HTTP_REFERER','/')
    return HttpResponseRedirect(url) 

@login_required
def comment_ding(request, id):
    comment = get_object_or_404(CommentWithVote, pk=id)
    person = request.user.get_profile()
    
    # increase the number of points the comment has
    if comment.votes is None:
        comment.votes = 1
    else:
        comment.votes += 1   
    
    # add the person to the list of voters (they can't vote again)
    comment.voters.add(person)
    comment.save()
    
    # finally, increase the karma of the comment writer
    comment_owner = get_object_or_404(Person, user__username=comment.user_name)
    if comment_owner.karma is None:
        comment_owner.karma = 1
    else:
        comment_owner.karma += 1
    comment_owner.save()
    
    url = request.META.get('HTTP_REFERER','/')
    return HttpResponseRedirect(url)

@login_required
def add_news(request):
    if request.method == 'POST':
        form = AddNewsForm(request.POST)
        if form.is_valid():
            
            # check if there's a news item been posted already with the same URL
            url = form.cleaned_data['url']
            if url in [x.url for x in NewsItem.objects.all()]:
                news_items = NewsItem.objects.filter(url=form.cleaned_data['url'])
                return render(request, "news/already_added.html", locals())
            
            if form.cleaned_data['as_user']:
                owner = form.cleaned_data['as_user']
            else:
                owner = request.user.get_profile()
                
            creation_args = {
                'date': datetime.now(),	
                'owner': owner,
                'title': form.cleaned_data['title'],
                'url': form.cleaned_data['url'],
                'text': form.cleaned_data['text'],
                'hashkey': uuid.uuid1().hex,
            }
            
            new_object = NewsItem.objects.create(**creation_args)
            url = reverse('news_home')
            return HttpResponseRedirect(url)
    
    else:
        form = AddNewsForm()
    
    
    return render(request, "news/forms/add_news_form.html", locals())
    

templates/news/already_added.html
{% extends "base.html" %}

{% load django_static comments %}

{% block pagetitle %}News{% endblock %}

{% block extracss %}
<style type="text/css">
span.votes {font-weight: bold; color: #666;}

.ding a:link, .ding a:visited {
    background-color: #e1e1e1;
    color: #666;
    display: block;
    float: left;
    font-weight: 900;
    height: 8px;
    margin-right: 5px;
    padding: 0 4px 7px;
    position: relative;
    top: 2px;
    width: 7px;
}

.ding a:hover {
  background-color: #D95700;
  color: #fff;
  text-decoration: none;
}

</style>
{% endblock %}

{% block addbutton %}
<a class="button" href="{% url add_news %}">Add News</a>
{% endblock %}

{% block content %}

<h2>Somebody already added this piece of news</h2>

<p>The URL you've submitted was submitted before by other users (see below):</p>


<ol id="newslist">
{% for n in news_items %}
<li>

	{% if n.url %}<a href="{{ n.url }}">{{ n }}</a>{% else %}{{ n }}{% endif %}
	
	<br/>
	<span class="small">
		{% if request.user.is_authenticated %}
		{% if request.user.get_profile in n.voters.all %}{% else %}
			<span class="ding"><a href="{% url news_ding n.hashkey %}">^</a></span>
		{% endif %}
		{% endif %}
		<span class="votes">{{ n.votes }} point{{ n.votes|pluralize }}</span> -
		<a href="{% url profile n.owner.user.username %}">{{ n.owner }}</a> - 
		{% get_comment_count for n as comments_count %}
		{% if comments_count %}
		<a href="{% url news_item n.hashkey %}">{{ comments_count }} comment{{ comments_count|pluralize }}</a> - 
		{% else %}
		<a href="{% url news_item n.hashkey %}">Discuss</a> - 
		{% endif %}
		{{ n.date|timesince }} ago
		
		
	</span>
</li>
{% endfor %}
</ol>

<p>To keep the news feed fresh and relevant (and also free of spam), we only allow URLs to be posted once. <br/><strong>You can join in the discussion on the threads above if you have something to say.</strong></p>


{% endblock %}

templates/news/index.html
{% extends "base.html" %}

{% load django_static %}

{% block pagetitle %}Home{% endblock %}

{% block extracss %}
<style type="text/css">
.block {
  background-color: #fff;
  border-radius: 8px;
  -webkit-border-radius: 8px;
  box-shadow: 0 1px 3px #999;
  padding: 15px 20px;
  float: left;
  width:200px;	
  border: 10px solid #f1f1f1;
  margin-right: 20px;
}

.block h2 {
  margin: 0;	
}

.block p {
  margin: 0;	
}

p.super-large {
  font-size: 32px;
  font-weight: bold;
  letter-spacing: -1px;
  color: #666;
}
</style>
{% endblock %}


{% block content %}

<p class="super-large">News, questions and answers covering the whole of China.</p>

<div class="block">
	<h2><a href="{% url news_home %}">News</a></h2>
	<p>Latest news from all news sources across China</p>
</div>

<div class="block">
	<h2><a href="{% url questions_home %}">Questions</a></h2>
	<p>Ask questions about China, get answers</p>
</div>

{% if request.user.is_authenticated %}
<div class="block">
	<h2>Invite a friend</h2>
	<p><a href="{% url invite_user %}">Invite a friend to the site</a></p>
</div>
{% endif %}
{% endblock %}

templates/news/news_home.html
{% extends "base.html" %}

{% load django_static comments %}

{% block pagetitle %}News{% endblock %}

{% block extrajs %}

<script type="text/javascript" charset="utf-8">  
function upVote(id) {    
  	$('li#' + id + ' .ding').css('display', 'none');
  	$.ajax({
  		type: "GET",
  		url: '{% url news_ding_ajax %}',
  		data: "xhr=true&id=" + id,	
	    success: function(data) {
	    	$('li#' + id + ' .number').replaceWith(data);	
	    }
	});
	return false;
}

$('#seen_reminder').click(function() {
	$('#voting').fadeOut(600);
	$('#newslist').unbind();
	$.ajax({
      type: "GET",
	  url: '{% url seen_voting_reminder %}',
	  data: "xhr=true"
	});
});

{% if request.user.get_profile.seen_voting_reminder %}{% else %}
$('#newslist').hover(function() {
	$('#voting').fadeIn(700);
});
{% endif %}

</script>  

{% endblock %}



{% block extracss %}
<style type="text/css">
span.votes {font-weight: bold; color: #666;}

.ding a:link, .ding a:visited, #voting span.ding {
    background-color: #e1e1e1;
    color: #666;
    display: block;
    float: left;
    font-weight: 900;
    height: 8px;
    margin-right: 5px;
    padding: 0 4px 7px;
    position: relative;
    top: 2px;
    width: 7px;
}

.ding a:hover {
  background-color: #D95700;
  color: #fff;
  text-decoration: none;
}

img.blocked {
  position: relative;
  top: 1px;
  left: 5px;	
}

span.url {
  font-size: 11px;
  font-weight: bold;	
}

#voting {
  display: none;	
}

#voting #seen_reminder {
  color: #226d28;	
  font-size: 11px;
}

#voting #seen_reminder:hover {
  cursor: pointer;
  text-decoration: underline;	
}

#rss {
  position: absolute;
  top: 0px;
  right: 0;
  background-color: #fff;
  padding: 5px 5px 5px 10px;
  border-top: 1px solid #e1e1e1;
  border-right: 1px solid #e1e1e1;
  border-left: 1px solid #f1f1f1;
  border-bottom: 1px solid #f1f1f1;	
  border-radius: 4px;
  font-size: 11px;
  font-weight: bold;
}

#rss img {
  float: right;	
}

#rss span {
  position: relative;
  top: 7px;
  margin-right: 5px;	
}

#rss a {
  color: #333;	
}

p.exp {
  color: #999;
  margin-top: 0;	
}

</style>
{% endblock %}

{% block addbutton %}
<a class="button" href="{% url add_news %}">Add News</a>
{% endblock %}

{% block content %}

<div id="rss">
<a href="/feeds/latest/"><span>Latest stories by RSS</span> <img src="/images/rss.png"/></a>
</div>

<div class="reminder" id="voting">
<h4>Vote for the stories you like!</h4>
<p><span class="ding">^</span> Ding the stories you like - they will stay on the homepage longer and other people are more likely to see them.</p>
<p>
<span id="seen_reminder">Don't show this again</span>
</p>
</div>

{% if latest %}
<p class="exp"><strong>Latest news stories ordered by date:</strong></p>
{% endif %}


<ol id="newslist">
{% for n in news %}
<li id="{{ n.id }}">
	{% if n.url %}<a href="{{ n.url }}">{{ n }}</a>{% else %}{{ n }}{% endif %}
		
		{% if n.is_blocked %}
		<img title="This website might be blocked by the Great Firewall" class="blocked" src="{% staticfile '/images/fire.png' %}">
		{% endif %}
	
	<br/>
	<span class="small">
		{% if request.user.is_authenticated %}
		{% if request.user.get_profile in n.voters.all %}{% else %}
			<span class="ding"><a href="#" onclick="upVote({{ n.id }})">^</a></span>
		{% endif %}
		{% endif %}
		<span class="votes"><span class="number">{{ n.votes }}</span> point{{ n.votes|pluralize }}</span> -
		<a href="{% url profile n.owner.user.username %}">{{ n.owner }}</a> - 
		{% get_comment_count for n as comments_count %}
		{% if comments_count %}
		<a href="{% url news_item n.hashkey %}">{{ comments_count }} comment{{ comments_count|pluralize }}</a> - 
		{% else %}
		<a href="{% url news_item n.hashkey %}">Discuss</a> - 
		{% endif %}
		<span class="url">{{ n.show_url }}</span>
		
		
		
	</span>
</li>
{% endfor %}
</ol>


{% endblock %}

templates/news/news_item.html
{% extends "base.html" %}

{% load comments %}

{% block pagetitle %}{{ news_item.title }}{% endblock %}


{% block extrajs %}

<script type="text/javascript" charset="utf-8">  
function upVote(id) {    
  	$('.' + id).css('display', 'none');
  	$.ajax({
  		type: "GET",
  		url: '{% url news_ding_ajax %}',
  		data: "xhr=true&id=" + id,	
	    success: function(data) {
	    	$('span.number').replaceWith(data);	
	    }
	});
	return false;
}

$('#comment_form').submit(function() {
	$('#submit_comment').css('opacity', '0.5');
	$('#submit_comment').unbind('click');
});
</script>  

{% endblock %}


{% block extracss %}
<style type="text/css">
input.hidden, input#id_honeypot, input#id_timestamp, input#id_content_type, input#id_object_pk {
  display: none;	
}

form {margin-top: 20px; width: 900px; float: left;}
label {float: right; margin-left: 20px;}
textarea {float: left; margin: 0 20px 20px 0;}
input.button {width: 200px;}

ul#comment-list {
  float: left;
  margin: 50px 0 0 0;
  padding: 30px 0 0 0;
  border-top: 3px dotted #e1e1e1;
  list-style-type: none;
  margin-bottom: 50px;	
}

ul#comment-list li {
  font-size: 14px;
  line-height: 1.5em;
  color: #333;	
  margin-bottom: 20px;
}

ul#comment-list li .meta {
  color: #666;
  font-size: 12px;
  font-weight: bold;	
}

ul.sublist {
  margin-left: 40px;
  margin-bottom: 40px;
  list-style-type: none;
  font-size: 14px;
}

ul.sublist li {
  margin: 20px 0 10px 0;	
}

.ding a:link, .ding a:visited {
    background-color: #e1e1e1;
    color: #666;
    display: block;
    float: left;
    font-weight: 900;
    height: 12px;
    margin-right: 5px;
    padding: 2px 4px 7px;
    position: relative;
    top: 0px;
    width: 9px;
}

.ding a:hover {
  background-color: #D95700;
  color: #fff;
  text-decoration: none;
}

ul#comment-list .ding a:link {
  width: 6px;	
  height: 10px;
  padding-top: 1px;
  top: 1px;
}

p.note {
  margin-top: 0;	
}

span.blocked, .blocked {
  color: #999;
  font-size: 12px;
  float: right;	
  position: relative;
  top: -3px;
}

span.blocked .ding {
    background-color: #e1e1e1;
    color: #666;
    font-weight: 900;
    height: 13px;
    float: left;
    margin-right: 5px;
    padding: 0px 4px 4px;
    position: relative;
    top: 2px;
    width: 7px;	
}

span.blocked a.ding:hover {
  background-color: #D95700;
  color: #fff;
  text-decoration: none;	
}

.small {
  font-size: 0.8em;
  color: #666;	
}

</style>
{% endblock %}

{% block addbutton %}
<a class="button" href="{% url add_news %}">Add News</a>
{% endblock %}

{% block content %}


<h2>{{ news_item.title }}</h2>
	<p class="">
		{% if request.user.is_authenticated %}
		{% if request.user.get_profile in news_item.voters.all %}{% else %}
			<span class="ding {{ news_item.id }}"><a href="#" onclick="upVote({{ news_item.id }})">^</a></span>
		{% endif %}
		{% endif %}
		<span class="grey"><span class="number">{{ news_item.votes }}</span> point{{ news_item.votes|pluralize }} - </span>
		
		
		<a href="{{ news_item.url }}">{{ news_item.url }}</a> 
		<span class="blocked">
		{% if news_item.is_blocked %}
			{{ news_item.blocked }} user{{ news_item.blocked|pluralize }} reported this URL is blocked in China
			<a title="Is this website censored for users in China by the Great Firewall?" class="ding" href="{% url news_blocked news_item.hashkey %}">^<a/>
		{% else %}
			Is this item blocked in China?
			<a title="Is this website censored for users in China by the Great Firewall?" class="ding" href="{% url news_blocked news_item.hashkey %}">^</a>
		{% endif %}
		</span>
	</p>



{% if news_item.text %}<p>{{ news_item.text }}</p>{% endif %}

{% if request.user.is_authenticated %}
	{% get_comment_form for news_item as form %}
	<form id="comment_form" action="{% comment_form_target %}" method="post">
	{% csrf_token %}
	
	<textarea id="id_comment" rows="5" cols="30" name="comment"></textarea>
	<p class="note"><strong>&laquo; Add your comment</strong><br/>Please stick to the guidelines, no trolling, flaming or racist language please.</p>
	<input class="hidden" id="id_name" type="text" value="{{ request.user.get_profile.user.username }}" name="name" maxlength="50" />
	<input class="hidden" type="text" name="email" id="id_email" value="{{ request.user.get_profile.email }}" />
	<input class="hidden" type="text" name="url" id="id_url" value="{{ siteurl }}" />
	{{ form.honeypot }}
	{{ form.content_type }}
	{{ form.object_pk }}
	{{ form.timestamp }}
	{{ form.security_hash }}
	<input type="hidden" class="hidden" name="next" value="{% url news_item news_item.hashkey %}" />
	
	<input id="submit-comment" type="submit" value="Submit" class="button">
	
	</form>
{% else %}
	<p>
		<strong><a href="{% url auth_login %}">Login</a> or <a href="{% url registration_register %}">signup</a> to post comments</strong>
	</p>
{% endif %}

{% get_comment_list for news_item as comment_list %}
<ul id="comment-list">
	{% for comment in comment_list %}
		<li>
			{{ comment.comment }}<br/>
			<span class="small">
				{% if request.user.get_profile in comment.voters.all %}{% else %}
					<span class="ding"><a href="{% url comment_ding comment.id %}">^</a></span>
				{% endif %}
				<span class="votes">{{ comment.votes }} point{{ comment.votes|pluralize }}</span> -
				<a href="{% url profile comment.user_name %}">{{ comment.user_name }}</a> - 
				{{ comment.submit_date|timesince }} ago
				{% if request.user.is_authenticated %}
				 - <a href="{% url comment_reply news_item.hashkey comment.pk %}">Reply</a>
				{% endif %}
			</span>
		
		{% get_comment_list for comment as 2_comment_list %}
		{% if 2_comment_list %}
		<ul class="sublist">
		{% for comment in 2_comment_list %}
			<li>
				{{ comment.comment }}<br/>
				<span class="small">
					{% if request.user.get_profile in comment.voters.all %}{% else %}
					<span class="ding"><a href="{% url comment_ding comment.id %}">^</a></span>
					{% endif %}
					<span class="votes">{{ comment.votes }} point{{ comment.votes|pluralize }}</span> -
					<a href="{% url profile comment.user_name %}">{{ comment.user_name }}</a> - 
					{{ comment.submit_date|timesince }} ago
				</span>
			</li>
		{% endfor %}
		</ul>
		{% endif %}
		</li>
	{% endfor %}
</ul>

{% endblock %}